tensorflow/tflite-support

tensorflow_lite_support/java/src/java/org/tensorflow/lite/support/image/ops/TransformToGrayscaleOp.java
Upload a new operator (TransformToGrayscaleOp)
=> Add new TransformToGrayscaleOp that transforms an image to grayscale

tensorflow_lite_support/examples/task/text/desktop/python/README.md
This folder is for Python demos which are based on the C++ Text Task APIs.
=> Added a folder for Python demos

tensorflow_lite_support/examples/task/text/desktop/python/README.md, tensorflow_lite_support/examples/task/text/desktop/python/nl_classifier_demo.py
Added a Python wrapper for NLClassifier
=> Feature python demo nlclassifier

tensorflow_lite_support/examples/task/text/desktop/python/BUILD, tensorflow_lite_support/examples/task/text/desktop/python/README.md, tensorflow_lite_support/examples/task/text/desktop/python/bert_nl_classifier_demo.py
Added a Python wrapper for BertNLClassifier
=> Feature python demo BertNLClassifier

tensorflow_lite_support/examples/task/audio/desktop/python/BUILD, tensorflow_lite_support/examples/task/audio/desktop/python/README.md, tensorflow_lite_support/examples/task/audio/desktop/python/audio_classifier_demo.py
Added a Python wrapper for audio classifier
=> Added Python demo for audio classifier

tensorflow_lite_support/examples/task/vision/desktop/python/BUILD, tensorflow_lite_support/examples/task/vision/desktop/python/README.md, tensorflow_lite_support/examples/task/vision/desktop/python/image_classifier_demo.py, tensorflow_lite_support/examples/task/vision/desktop/python/image_segmenter_demo.py, tensorflow_lite_support/examples/task/vision/desktop/python/object_detector_demo.py
Added a Python wrapper for Vision Task APIs
=> Added Python demos for Vision Task APIs

tensorflow_lite_support/metadata/python/metadata_writers/object_detector.py
Just a one word typo fix from 'dections' to 'detections'
=> Fix typo 'dections'

tensorflow_lite_support/ios/BUILD, tensorflow_lite_support/ios/Sources/TFLCommon.h, tensorflow_lite_support/ios/task/core/BUILD, tensorflow_lite_support/ios/task/core/Sources/TFLBaseOptions.h, tensorflow_lite_support/ios/task/processor/BUILD, tensorflow_lite_support/ios/task/processor/Sources/TFLClassificationOptions.h
Added build and header files of Objective C Framework for the following:
1. Base options
2. Classification Options
3. Common Error Codes
=> Added Common Base Option, Error Codes and Classification Option Header Files for Objective C

tensorflow_lite_support/c/task/processor/BUILD, tensorflow_lite_support/c/task/processor/category.h, tensorflow_lite_support/c/task/processor/classification_result.h, tensorflow_lite_support/c/task/processor/detection_result.h, tensorflow_lite_support/c/task/vision/BUILD, tensorflow_lite_support/c/task/vision/object_detector.h
Added Headers and Build Files for Object Detection C Wrappers
=> Headers for Object Detection C Wrappers

tensorflow_lite_support/tools/pip_package/rpi/Makefile, tensorflow_lite_support/tools/pip_package/rpi/build_arm_pip_package.sh
For release wheels, we don't need to provide "--nightly_flag".
PiperOrigin-RevId: 414884041
=> Update ARM build script for release

tensorflow_lite_support/python/test/task/vision/object_detector_test.py
- Added more tests for the API
=> Remaining tests for the Python Object Detector Task Library API

tensorflow_lite_support/python/task/text/text_embedder.py, tensorflow_lite_support/python/task/vision/image_embedder.py, tensorflow_lite_support/python/task/vision/object_detector.py, tensorflow_lite_support/python/test/task/text/text_embedder_test.py, tensorflow_lite_support/python/test/task/vision/image_embedder_test.py, tensorflow_lite_support/python/test/task/vision/object_detector_test.py
Fixes the issue: https://github.com/tensorflow/tflite-support/issues/760#issue-1170507302
=> Add create_from_file API to Python Task APIs

tensorflow_lite_support/examples/task/audio/desktop/audio_classifier_lib.cc, tensorflow_lite_support/python/task/audio/core/BUILD, tensorflow_lite_support/python/task/audio/core/tensor_audio.py, tensorflow_lite_support/python/test/task/audio/core/BUILD, tensorflow_lite_support/python/test/task/audio/core/tensor_audio_test.py
- Added `TensorAudio` class
- Added tests for `TensorAudio`
=> Python TensorAudio implementation and tests

tensorflow_lite_support/python/task/audio/audio_embedder.py, tensorflow_lite_support/python/task/audio/core/pybinds/BUILD, tensorflow_lite_support/python/task/audio/core/pybinds/_pywrap_audio_buffer.cc, tensorflow_lite_support/python/task/audio/core/tensor_audio.py, tensorflow_lite_support/python/task/audio/pybinds/BUILD, tensorflow_lite_support/python/task/audio/pybinds/_pywrap_audio_embedder.cc, tensorflow_lite_support/python/task/vision/image_classifier.py, tensorflow_lite_support/python/task/vision/object_detector.py, tensorflow_lite_support/python/task/vision/pybinds/BUILD, tensorflow_lite_support/python/task/vision/pybinds/_pywrap_image_classifier.cc, tensorflow_lite_support/python/task/vision/pybinds/_pywrap_object_detector.cc, tensorflow_lite_support/python/test/task/audio/audio_embedder_test.py, tensorflow_lite_support/python/test/task/vision/image_classifier_test.py, tensorflow_lite_support/python/test/task/vision/object_detector_test.py
Incorporated the new error handling changes to the following tasks
- AudioEmbedder
- ImageClassifier
- ObjectDetector
=> Python Task Library error handling update for remaining tasks

tensorflow_lite_support/python/task/vision/image_segmenter.py, tensorflow_lite_support/python/test/task/vision/BUILD, tensorflow_lite_support/python/test/task/vision/image_segmenter_test.py
- Fixed a `SegmentationOptions` initialization issue in `ImageSegmenterOptions`
- Added tests for category mask and confidence mask along with some additional tests
=> Remaining tests for the Python Image Segmenter Task Library

tensorflow_lite_support/opensource/opensource_only.files, tensorflow_lite_support/python/task/vision/image_segmenter.py, tensorflow_lite_support/tools/pip_package/BUILD, tensorflow_lite_support/tools/pip_package/build_pip_package.sh, tensorflow_lite_support/tools/pip_package/setup.py, tensorflow_lite_support/tools/pip_package/task_audio.__init__.py, tensorflow_lite_support/tools/pip_package/task_processor.__init__.py, tensorflow_lite_support/tools/pip_package/task_text.__init__.py, tensorflow_lite_support/tools/pip_package/task_vision.__init__.py
To reproduce locally, build the Pypi wheel by
```
bazel build -c opt tensorflow_lite_support/tools/pip_package:build_pip_package
./bazel-bin/tensorflow_lite_support/tools/pip_package/build_pip_package --dst wheels --nightly_flag
```
Code snippet for vision tasks:
```python
from tflite_support.task import vision
from tflite_support.task import core
from tflite_support.task import processor
base_options = core.BaseOptions(file_name=model_path)
classification_options = processor.ClassificationOptions(max_results=2)
options = vision.ImageClassifierOptions(base_options=base_options, classification_options=classification_options)
classifier = vision.ImageClassifier.create_from_options(options)
image = vision.TensorImage.create_from_file(image_path)
image_result = classifier.classify(image) …
```
=> Task Library: Add more tasks to the pip package

tensorflow_lite_support/python/task/vision/BUILD, tensorflow_lite_support/python/task/vision/image_searcher.py, tensorflow_lite_support/python/task/vision/pybinds/BUILD, tensorflow_lite_support/python/task/vision/pybinds/_pywrap_image_searcher.cc, tensorflow_lite_support/python/test/task/vision/BUILD, tensorflow_lite_support/python/test/task/vision/image_searcher_test.py
- Added ImageSearcher API files
- A sanity test to test image search w/ and w/o the bounding box.
=> Task Library: Python ImageSearcher API implementation

tensorflow_lite_support/python/test/task/vision/image_searcher_test.py, tensorflow_lite_support/tools/pip_package/BUILD, tensorflow_lite_support/tools/pip_package/task_vision.__init__.py
- Comprehensive tests for ImageSearcher
- Added image_searcher to the pip package
- To build the package locally,
```
bazel build -c opt tensorflow_lite_support/tools/pip_package:build_pip_package
./bazel-bin/tensorflow_lite_support/tools/pip_package/build_pip_package --dst wheels --nightly_flag
```
Code snippet for the image searcher task:
```python
from tflite_support.task import vision
from tflite_support.task import core
from tflite_support.task import processor
base_options = core.BaseOptions(file_name=model_path)
search_options = processor.SearchOptions(max_results=2)
embedding_options = processor.EmbeddingOptions(l2_normalize=True)
options = vision.ImageSearcherOptions(base_options=base_options, embedding_options=embedding_options, search_options=search_options)
searcher = …
```
=> Task Library: Comprehensive Python ImageSearcher tests

tensorflow_lite_support/c/task/processor/classification_result.h, tensorflow_lite_support/c/task/vision/image_classifier.cc
Updated C Classification Result struct to add a new member head_name which is used in audio classifier APIs.
=> Updated C classification Result Struct

tensorflow_lite_support/tools/pip_package/setup.py
=> Dump up the numpy version to 1.20.0

tensorflow_lite_support/ios/task/vision/sources/TFLImageClassifier.h, tensorflow_lite_support/ios/task/vision/sources/TFLImageSegmenter.h, tensorflow_lite_support/ios/task/vision/sources/TFLObjectDetector.h, tensorflow_lite_support/ios/test/task/vision/image_classifier/TFLImageClassifierTests.swift, tensorflow_lite_support/ios/test/task/vision/image_segmenter/TFLImageSegmenterTests.swift, tensorflow_lite_support/ios/test/task/vision/object_detector/TFLObjectDetectorTests.swift
1. Changed iOS Swift function names
2. Formatted code
3. Made init and new available for TFLImageClassifierOptions
=> Changed iOS Vision Swift Function Names

tensorflow_lite_support/c/task/audio/BUILD, tensorflow_lite_support/c/task/audio/audio_classifier.cc, tensorflow_lite_support/c/task/audio/audio_classifier.h, tensorflow_lite_support/c/task/audio/core/BUILD, tensorflow_lite_support/c/task/audio/core/audio_buffer.c, tensorflow_lite_support/c/task/audio/core/audio_buffer.h, tensorflow_lite_support/c/task/audio/utils/BUILD, tensorflow_lite_support/c/task/audio/utils/audio_buffer_cpp_c_utils.cc, tensorflow_lite_support/c/task/audio/utils/audio_buffer_cpp_c_utils.h, tensorflow_lite_support/c/test/task/audio/BUILD, tensorflow_lite_support/c/test/task/audio/audio_classifier_test.cc
1. Added C audio classifier implementation files.
2. Added basic tests
=> Added C Audio Classifier Implementation and Basic Tests

tensorflow_lite_support/python/test/task/text/nl_classifier_test.py
- Added a couple of tests for the API
=> Task Library: Remaining tests for the NLClassifier Python API

tensorflow_lite_support/python/test/task/text/bert_nl_classifier_test.py
=> Task Library: Remaining tests for the BertNLClassifier Python API

tensorflow_lite_support/python/task/text/pybinds/_pywrap_bert_question_answerer.cc, tensorflow_lite_support/python/test/task/text/bert_question_answerer_test.py
- Added a few more tests.
- Removed an unused stl import in the pybind layer.
=> Task Library: Added more tests for the BertQuestionAnswererer Python API

tensorflow_lite_support/tools/pip_package/BUILD, tensorflow_lite_support/tools/pip_package/task_processor.__init__.py, tensorflow_lite_support/tools/pip_package/task_text.__init__.py
To reproduce locally, build the Pypi wheel by
```bash
bazel build -c opt tensorflow_lite_support/tools/pip_package:build_pip_package
./bazel-bin/tensorflow_lite_support/tools/pip_package/build_pip_package --dst wheels --nightly_flag
```
Code snippet for text tasks:
```python
from tflite_support.task import text
from tflite_support.task import core
from tflite_support.task import processor
base_options = core.BaseOptions(file_name=model_path)
options = text.NLClassifierOptions(base_options=base_options)
classifier = text.NLClassifier.create_from_options(options)
text_classification_result = classifier.classify(text)
print(text_classification_result)
base_options = core.BaseOptions(file_name=model_path)
options = text.BertNLClassifierOptions(base_options=base_options)
classifier = …
```
=> Task Library: Add the newly implemented Python Text APIs to the pip package

tensorflow_lite_support/cc/task/processor/proto/BUILD, tensorflow_lite_support/cc/task/processor/proto/embedding_options_proto_inc.h, tensorflow_lite_support/ios/task/core/BUILD, tensorflow_lite_support/ios/task/core/sources/TFLBaseOptions+CppHelpers.h, tensorflow_lite_support/ios/task/core/sources/TFLBaseOptions+CppHelpers.mm, tensorflow_lite_support/ios/task/processor/BUILD, tensorflow_lite_support/ios/task/processor/sources/TFLEmbeddingOptions+Helpers.h, tensorflow_lite_support/ios/task/processor/sources/TFLEmbeddingOptions+Helpers.mm, tensorflow_lite_support/ios/task/processor/sources/TFLEmbeddingOptions.h, tensorflow_lite_support/ios/task/processor/sources/TFLEmbeddingOptions.m
Added Cpp Helpers for Base Options
Added Embedding Options and Cpp Helpers
=> Added iOS Image Searcher Options and Helpers

tensorflow_lite_support/cc/task/processor/proto/BUILD, tensorflow_lite_support/cc/task/processor/proto/search_options_proto_inc.h, tensorflow_lite_support/ios/task/core/BUILD, tensorflow_lite_support/ios/task/core/sources/TFLBaseOptions+CppHelpers.mm, tensorflow_lite_support/ios/task/core/sources/TFLBaseOptions.h, tensorflow_lite_support/ios/task/core/sources/TFLBaseOptions.m, tensorflow_lite_support/ios/task/core/sources/TFLExternalFile.h, tensorflow_lite_support/ios/task/core/sources/TFLExternalFile.m, tensorflow_lite_support/ios/task/processor/BUILD, tensorflow_lite_support/ios/task/processor/sources/TFLSearchOptions+Helpers.h, tensorflow_lite_support/ios/task/processor/sources/TFLSearchOptions+Helpers.mm, tensorflow_lite_support/ios/task/processor/sources/TFLSearchOptions.h, tensorflow_lite_support/ios/task/processor/sources/TFLSearchOptions.m
Added TFLSearchOptions and Helpers
=> Added iOS Search Options for Image Searcher

tensorflow_lite_support/ios/BUILD, tensorflow_lite_support/ios/task/core/BUILD, tensorflow_lite_support/ios/test/task/vision/image_searcher/BUILD, tensorflow_lite_support/ios/test/task/vision/image_searcher/TFLImageSearcherTests.swift
1. Added Swift Tests
2. Included image searcher in iOS vision framework for coocoapods
=> Added Swift Tests for iOS Image Searcher and include ImageSearcher API in TFLiteTaskVision pod

.gitignore, workspace1.bzl, workspace8.bzl
=> Bump Robolectric to 4.9

tensorflow_lite_support/acceleration/configuration/BUILD, tensorflow_lite_support/java/src/native/task/audio/BUILD, tensorflow_lite_support/java/src/native/task/text/BUILD, tensorflow_lite_support/java/src/native/task/vision/BUILD
Fixes https://github.com/tensorflow/tflite-support/issues/985 for me.
=> 16KB so support
